# https://stackoverflow.com/a/30173220
# docker exec -it <mycontainer> bash
# https://stackoverflow.com/a/44769468
# docker run -it image_name sh

volumes:
  postgres14-volume:
  mongo5.0-volume:

services:
  cache:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./src/database/config/redis.conf:/usr/local/etc/redis/redis.conf
    # https://stackoverflow.com/a/70706628
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redis", "--raw", "incr", "ping" ]

  # https://stackoverflow.com/questions/76201574/how-to-change-mongodb-password-in-docker-compose#76207336
  messages_db:
    image: mongo:5.0
    # https://www.baeldung.com/ops/docker-compose-restart-policies
    restart: unless-stopped
    env_file: .env
    healthcheck:
      # https://stackoverflow.com/a/74709736
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - mongo5.0-volume:/data/db

  users_db:
    image: postgres:14
    restart: unless-stopped
    shm_size: 10mb
    env_file: .env
    volumes:
      - postgres14-volume:/var/lib/postgresql/data
    ports:
      - 5004:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  reset-users_db:
    image: postgres:14
    env_file: .env
    environment:
      PGPASSWORD: $POSTGRES_PASSWORD
    depends_on:
      users_db:
        # https://stackoverflow.com/questions/65778431/using-depends-on-doesnt-start-required-container-but-starts-containers-dependi#76021926
        condition: service_healthy
    entrypoint: psql -h "$USERS_DB_ADDRESS" -p "$USERS_DB_PORT" -U "$POSTGRES_USER" -c 'DROP DATABASE IF EXISTS users;' -c 'DROP DATABASE IF EXISTS passwords;' -c 'CREATE DATABASE users;' -c 'CREATE DATABASE passwords;'

  init-db:
    build: .
    command: python ./src/database/init/init.py
    env_file: .env
    depends_on:
      reset-users_db:
        condition: service_completed_successfully
      messages_db:
        condition: service_healthy
      cache:
        condition: service_healthy

  auth-service:
    build: .
    command: python -m uvicorn --host 0.0.0.0 --port 5001 --reload src.auth.auth-service:app
    ports:
      - 5001:5001
    env_file: .env
    depends_on:
      init-db:
        condition: service_completed_successfully
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src/


  user-service:
    build: .
    command: python -m uvicorn --host 0.0.0.0 --port 5002 --reload src.user.user-service:app
    ports:
      - 5002:5002
    env_file: .env
    depends_on:
      init-db:
        condition: service_completed_successfully
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src/


  message-service:
    build: .
    command: python -m uvicorn --host 0.0.0.0 --port 5003 --reload src.message.message-service:app
    ports:
      - 5003:5003
    # https://stackoverflow.com/a/61357756
    env_file: .env
    depends_on:
      init-db:
        condition: service_completed_successfully

    # https://docs.docker.com/compose/gettingstarted/#step-4-edit-the-compose-file-to-use-compose-watch
    # docker compose up --watch
    develop:
      watch:
        # copies when something is updated, but image is not changed
        # - next docker compose up will be the same
        # https://docs.docker.com/compose/how-tos/file-watch/
        - action: sync # don't need to sync+restart - uvicorn restarts
          path: ./src
          target: /app/src/
