openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /message/{message_id}:
    get:
      summary: Find Message
      operationId: find_message_message__message_id__get
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: message_id
        in: path
        required: true
        schema:
          type: string
          title: Message Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /message:
    post:
      summary: Create Message
      operationId: create_message_message_post
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: message
        in: query
        required: true
        schema:
          type: string
          title: Message
      - name: to_email
        in: query
        required: true
        schema:
          type: string
          title: To Email
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: http://127.0.0.1:5001/token
